#+title: Crafting Streamlined Guix Configurations
#+subtitle: System Crafters Live - June 16, 2023
#+date: [2023-06-16 Fri]
#+video: u6WCnzKkKts

* Updates

** Speaking at LibrePlanet 2024

I was invited to give a keynote talk at the FSF's LibrePlanet 2024 conference!  The talk will be about building community around Free Software projects and creating a healthy ecosystem of contributors.

Here's the link for this year's LibrePlanet: https://libreplanet.org/2023/

I'll keep you posted for when registration opens.  I'd love to have a System Crafters meetup in Boston next spring!

** Subscribe to the Newsletter!

  https://systemcrafters.net/newsletter/

  Issue #004 just went out yesterday!

  https://systemcrafters.net/newsletter/sc-news-004.html
  
** Support my work!

  https://systemcrafters.net/how-to-help/#support-my-work
  
* Call for Community Projects

One thing I've been thinking about for a while is how to activate our community to collaborate on building new and useful things.  Emacs packages, Guix packages or configurations, Lisp-authored tools, really anything that would be useful to a system crafter!

To that end, I've created a new channel on Matrix and IRC for community members to discuss projects that they would like to collaborate on:

- *Matrix:* #systemcrafters-hacking:matrix.org
- *IRC:* #systemcrafters-hacking on irc.libera.chat

A few of us are there already discussing a few projects that you might be interested to join:

  - Fade is prototyping a new type of decentralized forum protocol based on NNTP
    and IPFS, written in Common Lisp:

    https://codeberg.org/fade/callisto

  - David is doing early work on simplifying Guix configurations in Crafted Guix:

    https://codeberg.org/SystemCrafters/crafted-guix

  - Bionicbabelfish asked for help in finishing this patch to add a Guix service to manage Docker containers as Shepherd services:
    https://codeberg.org/SystemCrafters/crafted-guix/src/commit/3bd0f448e1940b3fad9957c3314c1439842ebed0/projects/docker-container-service-type.org
    https://codeberg.org/SystemCrafters/crafted-guix/pulls/5
    https://issues.guix.gnu.org/58123

  - We should fix how Codeberg renders code blocks in Org Mode files:

    https://github.com/niklasfasching/go-org/issues/101

If you have your own idea for a project, please feel free to come discuss it with us!  These projects don't have to be under the "System Crafters" banner, but if you'd like to make it an official SC project, we can discuss giving you a repo under the System Crafters org on Codeberg.

* Simplifying Guix Configurations

To test the configuration in a VM:

#+begin_src sh

  $(guix system vm examples/sway-desktop.scm) -device virtio-vga-gl -display gtk,gl=on -m 2G -smp cores=2

#+end_src

... or ...

#+begin_src sh

  $(guix system vm examples/sway-desktop.scm) -device virtio-serial-pci,id=virtio-serial0,max_ports=16,bus=pci.0,addr=0x5 \
                                              -chardev spicevmc,name=vdagent,id=vdagent \
                                              -device virtserialport,nr=1,bus=virtio-serial0.0,chardev=vdagent,\
                                              name=com.redhat.spice.0

  guix shell virt-viewer -- remote-viewer -spice port=5930,disable-ticketing

#+end_src

Docs: https://guix.gnu.org/manual/devel/en/guix.html#Using-virt_002dviewer-with-Spice

#+begin_src sh

 (bootloader (bootloader-configuration
              (bootloader grub-bootloader)
              (targets '("/dev/vda"))))

 (file-systems (cons (file-system
                      (mount-point "/")
                      (device "/dev/vda1")
                      (type "ext4"))
                     %base-file-systems))
 

  ;; TODO: Import (gnu services spice)
  (define vm-config
    (crafted-config (add-system-services
                     (service spice-vdagent-service-type))))

#+end_src

Trying out the home configuration:

#+begin_src sh

  guix home -L ~/Projects/Code/crafted-guix/modules container examples/sway-desktop.scm 

#+end_src
